Hometask 4
Terospay/smart-home-2021 pull request #4
Opened 2021-04-28 16:08 UTC by Terospay

2021-04-28 16:37 UTC, a-ivanov requested changes

2021-04-28 16:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handler/SensorEventHandler.java
> +            LightHandler lightHandler = new LightHandler(smartHome);
Исправьте с 1 дз, перенесите обработчики в отдельные бины (см. гайд)

2021-04-28 16:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/adapter/EventHandlerAdapter.java
> +        Map<String, EventType> stringToSensorEvent = Map.of("LightIsOn", ru.sbt.mipt.oop.event.EventType.LIGHT_ON,
Перенесите мапу в бин, не нарушайте DIP на уровне конфигурации.

2021-04-28 16:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/adapter/EventHandlerAdapter.java
> +        return new SensorEvent(stringToSensorEvent.get(ccSensorEvent.getEventType()), ccSensorEvent.getObjectId());
Проверка на null

2021-04-30 06:13 UTC, a-ivanov requested changes

2021-04-30 06:13 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeConfiguration.java
> +        EventHandlerWithAlarmSafety lightHandlerWithAlarmSafety = new EventHandlerWithAlarmSafety(smartHome, lightHandler);
Так зачем так усложнять себе же жизнь? Оберните декоратором внутри бина обработчика, сделайте тип бина обработчика его интерфейсом, соберите здесь список интерфейсов обработчиков (см. Гайд по 4 дз)

2021-04-30 06:13 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/adapter/EventHandlerAdapter.java
> +        return new SensorEvent(stringToSensorEvent.get(ccSensorEvent.getEventType()), ccSensorEvent.getObjectId());
Так не исправлено же.

2021-04-30 17:41 UTC, Terospay commented on src/main/java/ru/sbt/mipt/oop/adapter/EventHandlerAdapter.java
> +        return new SensorEvent(stringToSensorEvent.get(ccSensorEvent.getEventType()), ccSensorEvent.getObjectId());
Странно, в последнем коммите лежит исправленная версия

2021-04-30 17:42 UTC, Terospay commented on src/main/java/ru/sbt/mipt/oop/adapter/EventHandlerAdapter.java
> +        Map<String, EventType> stringToSensorEvent = Map.of("LightIsOn", ru.sbt.mipt.oop.event.EventType.LIGHT_ON,
Тоже сделал, вроде как

2021-05-06 10:35 UTC, a-ivanov approved these changes

2021-05-06 10:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/adapter/EventHandlerAdapter.java
> +        return new SensorEvent(stringToSensorEvent.get(ccSensorEvent.getEventType()), ccSensorEvent.getObjectId());
Здесь этого не видно :(

2021-05-12 17:28 UTC, closed without merging